# permissions for end users to edit checks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edge-status
    app.kubernetes.io/managed-by: kustomize
  name: check-editor-role
rules:
- apiGroups:
  - probe.mikebz.com
  resources:
  - checks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - probe.mikebz.com
  resources:
  - checks/status
  verbs:
  - get
