---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - probe.mikebz.com
  resources:
  - checks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - probe.mikebz.com
  resources:
  - checks/finalizers
  verbs:
  - update
- apiGroups:
  - probe.mikebz.com
  resources:
  - checks/status
  verbs:
  - get
  - patch
  - update
